apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: ContactPoint
metadata:
  annotations:
    meta.upbound.io/cp-id: jedi-slack
  labels:
    testing.upbound.io/cp-name: jedi-slack
  name: jedi-slack
spec:
  providerConfigRef:
    name: grafana-cloud-provider-config
  forProvider:
    slack:
      - recipient: "C070HJSD0V7"
        tokenSecretRef: 
          key: "slack-token"
          name: "grafana-cloud-creds"
          namespace: "crossplane-system"
    name: jedi-slack