apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: secret-accessor-observability-bedrock-mongodb-public-key
  namespace: observability
spec: 
  member: "serviceAccount:observability-sa@prj-bdrck-preview-ctrlpln.iam.gserviceaccount.com"
  resourceRef: 
    external: "projects/677321866514/secrets/observability-bedrock-mongodb-public-key"
    kind: "SecretManagerSecret"
  role: "roles/secretmanager.secretAccessor"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: secret-accessor-observability-bedrock-mongodb-private-key
  namespace: observability
spec:
  member: "serviceAccount:observability-sa@prj-bdrck-preview-ctrlpln.iam.gserviceaccount.com"
  resourceRef:
    external: "projects/677321866514/secrets/observability-bedrock-mongodb-private-key"
    kind: "SecretManagerSecret"
  role: "roles/secretmanager.secretAccessor"
---
