apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongodb-grafana-credentials
  namespace: observability
spec:
  provider: gcp
  secretObjects:
    - data:
      - key: mongodbPublickey
        objectName: mongodbPublickey
      - key: mongodbPrivatekey
        objectName: mongodbPrivatekey
      secretName: mongodb-grafana
      type: Opaque
  parameters:
    secrets: |
      - resourceName: "projects/677321866514/secrets/observability-bedrock-mongodb-public-key/versions/latest"
        path: "mongodbPublickey"
      - resourceName: "projects/677321866514/secrets/observability-bedrock-mongodb-private-key/versions/latest"
        path: "mongodbPrivatekey"
