apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: observability-grafana-cloud-credentials
  namespace: observability
spec:
  parameters:
    cloudName: AzureChinaCloud
    keyvaultName: cncdpctlcnn3pre-keyvault
    objects: |
      array:
        - |
          objectName: mimirUser
          objectType: secret
        - |
          objectName: mimirPass
          objectType: secret
        - |
          objectName: mimirEndpoint
          objectType: secret
        - |
          objectName: lokiUser
          objectType: secret
        - |
          objectName: lokiPass
          objectType: secret
        - |
          objectName: lokiEndpoint
          objectType: secret
        - |
          objectName: tempoUser
          objectType: secret
        - |
          objectName: tempoPass
          objectType: secret
        - |
          objectName: tempoEndpoint
          objectType: secret
    tenantId: 3953396c-814c-4dbe-b543-ae4999978206
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: bdab89e2-9a9e-449b-8ac5-3ea87d9129a2
  provider: azure
  secretObjects:
  - data:
    - key: mimirUser
      objectName: mimirUser
    - key: mimirPass
      objectName: mimirPass
    - key: mimirEndpoint
      objectName: mimirEndpoint
    - key: lokiUser
      objectName: lokiUser
    - key: lokiPass
      objectName: lokiPass
    - key: lokiEndpoint
      objectName: lokiEndpoint
    - key: tempoUser
      objectName: tempoUser
    - key: tempoPass
      objectName: tempoPass
    - key: tempoEndpoint
      objectName: tempoEndpoint
    secretName: grafana-cloud
    type: Opaque