{
 "title": "Cert Manager",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Certificates Ready",
   "type": "stat",
   "description": "The number of certificates in the ready state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition) (certmanager_certificate_ready_status{cluster=\"$cluster\"})",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Soonest Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds{cluster=\"$cluster\"} > 0) - time()"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "description": "Status of the certificates. Values are True, False or Unknown.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(avg by (name, namespace, condition, exported_namespace) (certmanager_certificate_ready_status{cluster=\"$cluster\"} == 1), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(avg by (name, namespace, issuer_group, issuer_kind, issuer_name) (certmanager_certificate_expiration_timestamp_seconds{cluster=\"$cluster\"}) * 1000, \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    }
   ]
  },
  {
   "title": "Controller Sync Requests/sec",
   "type": "timeseries",
   "description": "The rate of controller sync requests.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller) (\n  rate(certmanager_controller_sync_call_count_total{cluster=\"$cluster\"}[$__rate_interval])\n)",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}