{
 "title": "gRPC Metrics OpenTelemetry",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "env", "label": "env", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({cluster=\"$env\", k8s_namespace_name=~\"$rpc_server|$rpc_client\"},k8s_namespace_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({cluster=\"$env\", k8s_namespace_name=\"$namespace\"},k8s_pod_name)"
    }
   },
   { "name": "route", "query": { "query": "label_values(http_route)" } },
   { "name": "rpc_method", "label": "rpc_method", "query": { "query": "label_values(rpc_method)" } },
   {
    "name": "grpc_status_code",
    "label": "grpc_status_code",
    "query": {
     "query": "label_values(rpc_grpc_status_code)"
    }
   },
   {
    "name": "rpc_server",
    "label": "namespace with rpc_server",
    "query": {
     "query": "label_values(rpc_server_duration_milliseconds_count{cluster=\"$env\"},k8s_namespace_name)"
    }
   },
   {
    "name": "rpc_client",
    "label": "namespace with rpc_client",
    "query": {
     "query": "label_values(rpc_client_duration_milliseconds_count{cluster=\"$env\"},k8s_namespace_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "gRPC server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests statistics (server)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", rpc_method=~\"$rpc_method\"}[$__rate_interval])) by (cluster, rpc_method, rpc_service, rpc_grpc_status_code) * $__interval_ms / 1000",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", rpc_method=~\"$rpc_method\", rpc_grpc_status_code=\"0\"}[$__rate_interval])) by (cluster, rpc_method, rpc_service, rpc_grpc_status_code)  * $__interval_ms / 1000 or on() vector(0)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", rpc_method=~\"$rpc_method\", rpc_grpc_status_code!~\"0\"}[$__rate_interval])) by (cluster, rpc_method, rpc_service, rpc_grpc_status_code)  * $__interval_ms / 1000 or on() vector(0)",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "gRPC Status code Description",
   "type": "text",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 12 },
   "options": {
    "content": "`OK (0)`\n\n`CANCELLED (1)`\n\n`UNKNOWN (2)`\n\n`INVALID_ARGUMENT (3)`\n\n`DEADLINE_EXCEEDED (4)`\n\n`NOT_FOUND (5)`\n\n`ALREADY_EXISTS (6)`\n\n`PERMISSION_DENIED (7)`\n\n`RESOURCE_EXHAUSTED (8)`\n\n`FAILED_PRECONDITION (9)`\n\n`ABORTED (10)`\n\n`OUT_OF_RANGE (11)`\n\n`UNIMPLEMENTED (12)`\n\n`INTERNAL ERROR (13)`\n\n`UNAVAILABLE (14)`\n\n`DATA_LOSS (15)`\n\n`UNAUTHENTICATED (16)`\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 12 },
   "targets": [
    {
     "expr": "(sum(rate(rpc_server_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=~\"$namespace\", rpc_method=~\"$rpc_method\"}[$__rate_interval])) by ( rpc_method, rpc_service, rpc_grpc_status_code)) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=~\"$namespace\", rpc_method=~\"$rpc_method\", rpc_grpc_status_code!~\"0\"}[$__rate_interval])) by (rpc_method, rpc_service, rpc_grpc_status_code) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "gRPC clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Requests statistics (client)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", rpc_method=~\"$rpc_method\"}[$__rate_interval])) by (cluster, rpc_method, rpc_service, rpc_grpc_status_code) * $__interval_ms / 1000",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(rpc_client_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", rpc_method=~\"$rpc_method\", rpc_grpc_status_code=\"0\"}[$__rate_interval])) by (cluster, rpc_method, rpc_service, rpc_grpc_status_code)  * $__interval_ms / 1000 or on() vector(0)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(rpc_client_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", rpc_method=~\"$rpc_method\", rpc_grpc_status_code!~\"0\"}[$__rate_interval])) by (cluster, rpc_method, rpc_service, rpc_grpc_status_code)  * $__interval_ms / 1000 or on() vector(0)",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "Errors Count (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=~\"$namespace\", rpc_method=~\"$rpc_method\", rpc_grpc_status_code!~\"0\"}[$__rate_interval])) by ( rpc_method, rpc_service, rpc_grpc_status_code) * $__interval_ms / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Count (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "(sum(rate(rpc_client_duration_milliseconds_count{cluster=~\"$${env}\", k8s_namespace_name=~\"$namespace\", rpc_method=~\"$rpc_method\"}[$__rate_interval])) by ( rpc_method, rpc_service, rpc_grpc_status_code)) * $__interval_ms / 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}