{
 "title": "HTTP Metrics OpenTelemetry",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "env", "label": "env", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({cluster=\"$env\"},k8s_namespace_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({cluster=\"$env\", k8s_namespace_name=\"$namespace\"},k8s_pod_name)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values({cluster=~\"$env\", k8s_namespace_name=~\"$namespace\"},http_route)"
    }
   },
   { "name": "http_method", "query": { "query": "label_values(http_method)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests statistics",
   "type": "table",
   "description": "This panel is the actual count of the request in the time window defined. The sum of the requests might not be 100% accurate due to Prometheus metrics calculations involving rates.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", http_route=~\"$${route}\"}[$__rate_interval]) * $__interval_ms) by (cluster, http_request_method, http_route) /1000",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", http_route=~\"$${route}\", http_response_status_code=~\"2..\"}[$__rate_interval])* $__interval_ms) by (cluster, http_request_method, http_route) /1000 or on() vector(0)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", http_route=~\"$${route}\", http_response_status_code=~\"3..\"}[$__rate_interval])* $__interval_ms) by (cluster, http_request_method, http_route) /1000 or on() vector(0)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", http_route=~\"$${route}\", http_response_status_code=~\"4..\"}[$__rate_interval])* $__interval_ms) by (cluster, http_request_method, http_route) /1000 or on() vector(0)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", http_route=~\"$${route}\", http_response_status_code=~\"5..\"}[$__rate_interval])* $__interval_ms) by (cluster, http_request_method, http_route) /1000 or on() vector(0)",
     "legendFormat": "x"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum{cluster=~\"$${env}\", k8s_namespace_name=~\"$namespace\", http_route=~\"$${route}\"}[$__rate_interval])* $__interval_ms) by (cluster, http_request_method, http_route) /1000",
     "legendFormat": "x"
    },
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_sum{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", http_route=~\"$${route}\"}[$__rate_interval])) by(cluster, http_request_method, http_route) / sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=\"$namespace\", http_route=~\"$${route}\"}[$__rate_interval])) by(cluster, http_request_method, http_route) >= 0) OR on() vector(0)",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "Total Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=~\"$namespace\", http_route=~\"$${route}\"}[$__rate_interval])) by (cluster, http_route, http_request_method)) * $__interval_ms * 3/ 1000",
     "legendFormat": " {{http_request_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Total Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{cluster=~\"$${env}\", k8s_namespace_name=~\"$namespace\", http_route=~\"$${route}\", http_response_status_code=~\"4..|5..\"}[$__rate_interval])) by (cluster, http_route, http_request_method)  * $__interval_ms / 1000",
     "legendFormat": "{{http_request_method}} {{http_route}}"
    }
   ]
  }
 ]
}