{
 "title": "Kafka Metrics (auto-instrumented)",
 "description": "Dashboard for cvc-edge-processor service",
 "tags": [ "" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({cluster=\"$cluster\"},k8s_namespace_name)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values({cluster=\"$cluster\", k8s_namespace_name=\"$namespace\"},service_name)"
    }
   },
   {
    "name": "percentile",
    "query": "0.999999, 0.99, 0.90, 0.75, 0.66, 0.50, 0.25, 0.10, 0.01"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_records_lag{cluster=\"$cluster\", job=\"$job\"}) by(topic)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Fetch Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_latency_avg{job=\"$job\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Partition Assignments, by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_assigned_partitions{cluster=\"$cluster\",job=\"$job\"}) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Records In per Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_size_avg{job=\"$job\",cluster=\"$cluster\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records Out per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kafka_producer_record_send_total{job=\"$job\",cluster=\"$cluster\"}[$__range])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records Out ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_record_send_total{job=\"$job\",cluster=\"$cluster\"}[10m])) by (topic)",
     "legendFormat": "{{total}}"
    }
   ]
  },
  {
   "title": "Amount of data consumed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_consumer_fetch_total{cluster=\"$cluster\", k8s_namespace_name=~\"$namespace\", job=~\"$job\", topic!=\"topic-empty\"}[$__range])) by (topic) > 0",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}