{
 "title": "KubeVela System",
 "description": "KubeVela System Overview",
 "tags": [
  "kubevela",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values({cluster=\"$cluster\", k8s_namespace_name=~\"vela-system\"},k8s_pod_name)"
    }
   },
   {
    "name": "rate_interval",
    "query": "3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview of vela-core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Applications",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\".*kubevela.*\"})"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",phase=\"running\",k8s_pod_name=~\".*kubevela.*\"})"
    }
   ]
  },
  {
   "title": "TerminatedWorkflow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",phase=\"workflowTerminated\",k8s_pod_name=~\".*kubevela.*\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container=\"kubevela\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",k8s_container_name=\"kubevela\",k8s_pod_name=~\"$pod\"}) / sum(container_spec_memory_limit_bytes{cluster=~\"$cluster\",k8s_container_name=\"kubevela\",k8s_pod_name=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "WorkflowFailed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",phase=\"workflowFailed\",k8s_pod_name=~\".*kubevela.*\"}) "
    }
   ]
  },
  {
   "title": "Deleting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",phase=\"deleting\",k8s_pod_name=~\".*kubevela.*\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_pod_container_info{cluster=~\"$cluster\",container=\"kubevela\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(application_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}))"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_info{cluster=~\"$cluster\",container=\"kubevela\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_receive_bytes_total[5m])) by (pod)) + \nsum(sum(kube_pod_container_info{cluster=~\"$cluster\",container=\"kubevela\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_transmit_bytes_total[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "RunningWorkflow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",phase=\"runningWorkflow\",k8s_pod_name=~\".*kubevela.*\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container=\"kubevela\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",container=\"kubevela\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\",pod=~\"$pod\"}) by (created_by_name, uid, pod, pod_ip, node) * on(pod) group_left() sum(kube_pod_container_info{cluster=~\"$cluster\",container=\"kubevela\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\"} * (kube_pod_status_phase{cluster=~\"$cluster\"} > 0)) by (pod, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{cluster=~\"$cluster\"} * (kube_pod_status_ready{cluster=~\"$cluster\"} > 0)) by (pod, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{cluster=~\"$cluster\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}) by (pod, container)) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",container=\"kubevela\"}) by (pod) / sum(container_spec_memory_limit_bytes{cluster=~\"$cluster\",container=\"kubevela\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container=\"kubevela\"}[5m])) by (pod) / sum(container_spec_cpu_quota{cluster=~\"$cluster\",container=\"kubevela\"}) by (pod) * 1e5"
    },
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\"}) by (pod, controller_core_oam_dev_shard_id)"
    }
   ]
  },
  { "title": "Controller Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Controller Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Controller Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (result, controller)",
     "legendFormat": "{{result}}: {{controller}}"
    }
   ]
  },
  {
   "title": "Average Reconcile Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (controller) / sum(rate(controller_runtime_reconcile_time_seconds_count{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{controller=\"application\",cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) / sum(rate(controller_runtime_reconcile_time_seconds_count{controller=\"application\",cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"application\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"application\",app_kubernetes_io_name=\"vela-core\"}[$rate_interval])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Reconcile Stage Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kubevela_app_reconcile_time_seconds_sum{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\",stage=~\"[^.]+\"}[$rate_interval])) by (stage) / sum(rate(kubevela_app_reconcile_time_seconds_count{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\",stage=~\"[^.]+\"}[$rate_interval])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Client Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kubevela_controller_client_request_time_seconds_count{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (kind, verb)",
     "legendFormat": "{{verb}}: {{kind}}"
    }
   ]
  },
  {
   "title": "Client Request Avg Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kubevela_controller_client_request_time_seconds_sum{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (kind, verb) / sum(rate(kubevela_controller_client_request_time_seconds_count{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (kind, verb)",
     "legendFormat": "{{verb}}: {{kind}}"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Number of Applications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(application_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}) by (phase)",
     "legendFormat": "Phase: {{phase}}"
    }
   ]
  },
  {
   "title": "Number of Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(workflow_step_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"})",
     "legendFormat": "All"
    },
    {
     "expr": "sum(workflow_step_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}) by (step_type)",
     "legendFormat": "Type: {{step_type}}"
    }
   ]
  },
  {
   "title": "StepStatus Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(workflow_step_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}) by (phase)",
     "legendFormat": "Status: {{phase}}"
    },
    {
     "expr": "sum(workflow_step_phase_number{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}) by (step_type, phase)",
     "legendFormat": "{{step_type}}: {{phase}}"
    }
   ]
  },
  {
   "title": "Workflow Initialize Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(workflow_initialized_num{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval]))",
     "legendFormat": "Initialize Rate"
    }
   ]
  },
  {
   "title": "Workflow Average Complete Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(workflow_finished_time_seconds_sum{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (phase) / sum(rate(workflow_finished_time_seconds_count{cluster=~\"$cluster\",k8s_pod_name=~\"$pod\"}[$rate_interval])) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "Overview of cluster-gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Avg Latency (by verb & resource)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ocm_proxy_proxied_request_duration_seconds_sum[$rate_interval])) by (verb, resource) / sum(rate(ocm_proxy_proxied_request_duration_seconds_count[$rate_interval])) by (verb, resource)",
     "legendFormat": "{{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "QPS (by verb & resource)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum(rate(ocm_proxy_proxied_request_duration_seconds_count[$rate_interval])) by (verb, resource)",
     "legendFormat": "{{verb}} {{resource}}"
    }
   ]
  },
  {
   "title": "Avg Latency (by cluster)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(ocm_proxy_proxied_request_duration_seconds_sum[$rate_interval])) by (cluster) / sum(rate(ocm_proxy_proxied_request_duration_seconds_count[$rate_interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "QPS (by cluster)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum(rate(ocm_proxy_proxied_request_duration_seconds_count[$rate_interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}