{
 "title": "MongoDB Atlas",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "project",
    "label": "mongodb_project",
    "query": {
     "query": "label_values(mongodb_atlas_project_name)"
    }
   },
   {
    "name": "db_type",
    "label": "db_type",
    "query": {
     "query": "label_values(mongodb_atlas_process_type_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Displays the number of collections in the database.\nMonitor collections to determine restart times, continuous backup performance, and stability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mongodbatlas_process_connections{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\""
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "Returned displays the documents per second returned.\n\nInserted displays the documents per second inserted.\n\nUpdated displays the documents per second updated.\n\nDeleted displays the documents per second deleted.\n\nMonitor document metrics to measure the work MongoDB completes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_db_document_rate_per_second{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\",document_status=\"{{document_status}}\""
    }
   ]
  },
  {
   "title": "Tickets Available",
   "type": "timeseries",
   "description": "Tickets Available Read displays the number of read tickets available to the WiredTiger storage engine. Read tickets represent the number of concurrent read operations allowed into the storage engine. When this value reaches zero, new read requests might queue until a read ticket becomes available.\n\nTickets Available Write displays the number of write tickets available to the WiredTiger storage engine. Write tickets represent the number of concurrent write operations allowed into the storage engine. When this value reaches zero, new write requests might queue until a write ticket becomes available.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mongodbatlas_process_tickets{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", ticket_type=\"{{ticket_type}}\""
    }
   ]
  },
  {
   "title": "Assert Events",
   "type": "timeseries",
   "description": "ASSERT_REGULAR displays the average rate of regular asserts raised per second over the selected sample period.\n\nASSERT_WARNING displays the average rate of warnings per second over the selected sample period.\n\nASSERT_MSG displays the average rate of message asserts per second over the selected sample period. These internal server errors have a well-defined text string. Atlas logs stack traces for these.\n\nASSERT_USER displays the average rate of user asserts per second over the selected sample period. This metric includes asserts that a user generates, such as out of disk space or duplicate key errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_asserts_per_second{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", assert_type=\"{{assert_type}}\""
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "The rate of network input/output (I/O) in bytes per second for a MongoDB Atlas process.\nBy analyzing this metric, administrators and operators can gain visibility into the network I/O patterns and identify any potential bottlenecks, spikes, or anomalies in network activity that may impact the performance and reliability of the MongoDB Atlas deployment.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_network_io_bytes_per_second{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", direction=\"{{direction}}\""
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "\t\nDisplays the total consumption of memory in gigabytes at a particular point in time:\n\nmemory_resident (replica set) or memory resident (sharded cluster) displays the memory that the MongoDB process running on a node consumes. This metric excludes the consumption of other processes and does not represent the total memory that the node consumes.\n\nmemory_virtual (replica set) or memory virtual (sharded cluster) displays the memory reserved in disk to act as swap space.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_memory_usage_bytes{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", memory_state=\"{{memory_state}}\""
    }
   ]
  },
  {
   "title": "Query Targeting",
   "type": "timeseries",
   "description": "Displays the efficiency of read operations run on MongoDB:\n\nScanned Objects to Returned (replica set) or scanned objects / returned (sharded cluster) displays the number of documents scanned to return one document.\n\nScanned Keys to Returned (replica set) or scanned keys / returned (sharded cluster) displays the number of index keys scanned to return one document.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "mongodbatlas_process_db_query_targeting_scanned_per_returned{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", scanned_type=\"{{scanned_type}}\""
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "timeseries",
   "description": "Displays the average rate of page faults on this process per second over the selected sample period. In non-Windows environments this applies to hard page faults only.\n\nMonitor page faults to determine whether to increase your memory.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "mongodbatlas_process_page_faults_per_second{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\""
    }
   ]
  },
  {
   "title": "Operation Execution Times",
   "type": "timeseries",
   "description": "Displays the average time in milliseconds to execute the following operations:\n\navg ms/read (replica set) or execution time reads (sharded cluster)\n\navg ms/write (replica set) or execution time writes (sharded cluster)\n\navg ms/command (replica set) or execution time commands (sharded cluster)\n\nMonitor execution time for an increase in read operations to optimize queries and indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_db_operations_time_milliseconds_total{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", execution_type=\"{{execution_type}}\""
    }
   ]
  },
  {
   "title": "Opcounters",
   "type": "timeseries",
   "description": "Displays the number of the following operations per second run on a MongoDB process since the process last started:\n\ncommand (replica set) or cmd (sharded cluster)\n\nquery\n\ninsert\n\ndelete\n\nupdate\n\ngetmore\n\nMonitor MongoDB operations to validate performance issues related to high workloads. Confirm the type of operations responsible for the load.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "mongodbatlas_process_db_operations_rate_per_second{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", operation=\"{{operation}}\""
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "timeseries",
   "description": "Displays the following information:\n\ndirty (replica set) or cache dirty (sharded cluster) displays the total dirty bytes cached in memory for serving reads and writes.\n\nused (replica set) or cache used (sharded cluster) displays the total bytes cached in memory for serving reads and writes.\n\nThese metrics include both indexes and data from the working set.\n\nSustained high cache usage indicates the RAM is too small for your workloads. Optimize your queries to avoid frequent disk reads. If write operations make cache usage high, throttle them.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_cache_size_bytes{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", cache_status=\"{{cache_status}}\""
    }
   ]
  },
  {
   "title": "Scan And Order",
   "type": "timeseries",
   "description": "Displays the number of operations per second returning results that required a sort in-memory.\n\nMonitor this metric to identify whether your queries need indexes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "mongodbatlas_process_db_operations_rate_per_second{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\", operation=\"scan_and_order\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", operation=\"{{operation}}\""
    }
   ]
  },
  {
   "title": "Query Executor",
   "type": "timeseries",
   "description": "Displays the following information:\n\nIndex Items Scanned displays the number of index items scanned per second.\n\nDocuments Scanned displays the number of documents scanned per second.\n\nMonitor the query executor to determine whether you have any inefficient queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "mongodbatlas_process_db_query_executor_scanned_per_second{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", scanned_type=\"{{scanned_type}}\""
    }
   ]
  },
  {
   "title": "Oplog GB/Hour",
   "type": "timeseries",
   "description": "Displays the average rate in gigabytes of \noplog\n data that the primary generates per hour.\n\nMonitor oplog data to determine whether you have to increase the oplog size.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_oplog_rate_gibibytes_per_hour{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\""
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "description": "Displays the following information:\n\ntotalOpen displays the number of cursors that the server maintains for clients.\n\ntotalTimedOut displays the average rate of cursors that have timed out per second over the selected sample period.\n\nMonitor cursors to close unnecessary cursors and reduce the timeout configuration in the application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "mongodbatlas_process_cursors{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", cursor_state=\"{{cursor_state}}\""
    }
   ]
  },
  {
   "title": "DB storage",
   "type": "timeseries",
   "description": "\t\nDisplays the following information:\n\nstorageSize (replica set) or db storage size (sharded cluster) displays the sum total amount of on-disk storage space allocated for document storage across all databases.\n\nData Size (serverless instance), dataSize (replica set), or db data size (sharded cluster) displays the amount of storage space in bytes that your stored data uses.\n\ndb data size without system displays the sum total size in bytes of the document data (including the padding factor) across non-system databases.\n\nAtlas retrieves database metrics every 20 minutes by default but adjusts frequency when necessary to reduce the impact on database performance.\n\nMonitor storage space to determine whether to use disk auto-scaling or manually increase the disk size.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodbatlas_db_size_bytes{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", mongodb_atlas_db_name=\"{{mongodb_atlas_db_name}}\", object_type=\"{{object_type}}\""
    }
   ]
  },
  {
   "title": "Queued operations",
   "type": "timeseries",
   "description": "\t\nDisplays the following information:\n\nGLOBAL_LOCK_CURRENT_QUEUE_TOTAL displays the number of operations queued waiting for any lock.\n\nGLOBAL_LOCK_CURRENT_QUEUE_READERS displays the number of operations queued waiting for a read lock.\n\nGLOBAL_LOCK_CURRENT_QUEUE_WRITERS displays the number of operations queued waiting for a write lock.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "mongodbatlas_process_global_lock{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", global_lock_state=\"{{global_lock_state}}\""
    }
   ]
  },
  {
   "title": "Cache Activity",
   "type": "timeseries",
   "description": "Displays the following information:\n\nreadInto (replica set) or cache read into (sharded cluster) displays the rate in bytes per second of data read from disk into memory to service queries.\n\nwrittenFrom (replica set) or cache written from (sharded cluster) displays the rate in bytes per second of data written from memory into disk to service writes.\n\nMonitor the MongDB cache, which stores frequently accessed data in memory to service queries faster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_cache_io_bytes{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", cache_direction=\"{{cache_direction}}\""
    }
   ]
  },
  {
   "title": " Replication Headroom ",
   "type": "timeseries",
   "description": "Displays the difference between the primary's replication oplog window and the secondary's replication lag.\n\nMonitor replication headroom to determine whether the secondary might fall off the oplog.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_oplog_time_seconds{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name!~\"!REPLICA_PRIMARY\", oplog_type=\"master_lag_time_diff\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\""
    }
   ]
  },
  {
   "title": "Catalog",
   "type": "timeseries",
   "description": "Displays the following information:\n\ntotal databases displays the total number of non-system databases.\n\ntotal collections displays the total number of collections across all non-system databases.\n\ntotal views displays the total number of views across all non-system databases.\n\ntotal indexes displays the total number of indexes across all non-system collections.\n\nMonitor catalog counts to prevent an excessive number of databases, collections, views, or indexes from causing startup failures when you upgrade a cluster tier.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "mongodbatlas_db_counts{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\", object_type!~\"object\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\", object_type=\"{{object_type}}\", mongodb_atlas_db_name=\"{{mongodb_atlas_db_name}}\""
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "Displays the approximate number of seconds the secondary is behind the primary in write application.\n\nMonitor replication lag to determine whether the secondary might fall off the oplog.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_oplog_time_seconds{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\", oplog_type=\"slave_lag_master_time\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\""
    }
   ]
  },
  {
   "title": "Replication Oplog Window",
   "type": "timeseries",
   "description": "\t\nDisplays the estimated average number of hours of database operations available in the primary's replication oplog, based on oplog churn. If replication lag on a secondary node exceeds the replication oplog window, and replication headroom reaches zero, a \nfull resync\n is required for that node to become healthy again.\n\nMonitor the replication oplog window, together with replication headroom, to determine whether the secondary may soon require a full resync. The replication oplog window often helps to determine in advance the resilience of secondaries to planned and unplanned outages.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "mongodbatlas_process_oplog_time_seconds{cluster=~\"$cluster\", mongodb_atlas_project_name=~\"$project\", mongodb_atlas_process_type_name=~\"$db_type\", oplog_type=\"master_time\"}",
     "legendFormat": "cluster=\"{{cluster}}\", project_name=\"{{mongodb_atlas_project_name}}\", db_type=\"{{mongodb_atlas_process_type_name}}\""
    }
   ]
  }
 ]
}