{
 "title": "Network TCP Load Balancer",
 "tags": [
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Network TCP Load Balancer Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 5 charts for the related [network TCP load balancer metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-loadbalancing), including `RTT latencies`, `Ingress TCP packets`, `Ingress TCP bytes`, `Egress TCP packets`, and `Egress TCP bytes`."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "RTT latencies [95/50/5 PERCENTILE]",
   "type": "timeseries",
   "description": "Round-trip time latencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/rtt_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     },
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/l3/external/rtt_latencies"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/rtt_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     },
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/l3/external/rtt_latencies"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project"
     }
    },
    {
     "timeSeriesList": {
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/l3/external/rtt_latencies"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Ingress TCP packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/ingress_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Ingress TCP bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/ingress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Egress TCP packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/egress_packets_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Egress TCP bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "tcp_lb_rule"
      ],
      "groupBys": [
       "resource.label.load_balancer_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/l3/external/egress_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}