{
 "title": "Otel Collector Support Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(otelcol_process_uptime_total,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tail Sampling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New Trace Ids For 1minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(otelcol_processor_tail_sampling_new_trace_id_received_total{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Of Taces Dropped Too Early",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(otelcol_processor_tail_sampling_sampling_trace_dropped_too_early_total{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Memory Traces Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(cluster, job) (last_over_time(otelcol_processor_tail_sampling_sampling_traces_on_memory{cluster=~\"$cluster\"}[$__interval]))",
     "legendFormat": "{{cluster}} - {{job}}"
    }
   ]
  },
  {
   "title": "Percentile Time For Traces In Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.99 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.95 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.75 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.5 - {{cluster}}"
    },
    {
     "expr": "avg by(cluster) (rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_bucket{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "mean - {{cluster}}"
    }
   ]
  },
  {
   "title": "Percentile Time Of Incomming Span After Sampling Decision",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.99 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.95 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.75 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.5 - {{cluster}}"
    },
    {
     "expr": " avg by( cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "mean - {{cluster}}"
    }
   ]
  },
  {
   "title": "Rate of Late Spans Per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_count[$__rate_interval]))",
     "legendFormat": "rate - {{cluster}}"
    }
   ]
  },
  {
   "title": "Count of Late Spans Per Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by(cluster) (otelcol_processor_tail_sampling_sampling_late_span_age_count)",
     "legendFormat": "count - {{cluster}}"
    }
   ]
  },
  {
   "title": "Percentile Processing Time Per Decision Run",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_decision_timer_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.99 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_decision_timer_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.95 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_decision_timer_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.75 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_decision_timer_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.5 - {{cluster}}"
    },
    {
     "expr": "avg by(cluster) (rate(otelcol_processor_tail_sampling_sampling_decision_timer_latency_bucket{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "mean - {{cluster}}"
    }
   ]
  },
  {
   "title": "Sum Of Policy Evaluation Errors per Cluster",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by(cluster) (otelcol_processor_tail_sampling_sampling_policy_evaluation_error_total{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sum Of Dropped Too Early Traces per Cluster",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "sum by(cluster) (otelcol_processor_tail_sampling_sampling_trace_dropped_too_early_total{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time per Percentile Of Incomming Span After Sampling Decision",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.99 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.95 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.90 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.75 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m])))",
     "legendFormat": "0.5 - {{cluster}}"
    },
    {
     "expr": " avg by( cluster) (rate(otelcol_processor_tail_sampling_sampling_late_span_age_bucket{cluster=~\"$cluster\"}[10m]))",
     "legendFormat": "mean - {{cluster}}"
    }
   ]
  },
  { "title": "Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Rate of Resolution Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(cluster, success) (rate(otelcol_loadbalancer_backend_outcome_total{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "success: {{success}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, cluster) (rate(otelcol_loadbalancer_backend_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.99 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, cluster) (rate(otelcol_loadbalancer_backend_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.95 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le, cluster) (rate(otelcol_loadbalancer_backend_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.75 - {{cluster}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, cluster) (rate(otelcol_loadbalancer_backend_latency_bucket{cluster=~\"$cluster\"}[1m])))",
     "legendFormat": "0.5 - {{cluster}}"
    }
   ]
  },
  {
   "title": "Rate of Backend Monitor Collector Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(otelcol_loadbalancer_num_backend_updates_total{cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "success: {{success}} - {{cluster}}"
    }
   ]
  },
  {
   "title": "Count of Gateway Collectors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum by(cluster) (last_over_time(otelcol_loadbalancer_num_backends{cluster=~\"$cluster\"}[$__interval]))",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}