{
 "title": "Redis Monitoring",
 "description": "This dashboard is for monitoring redis (memorystore) for bedrock projects",
 "tags": [
  "Redis",
  "cloud-monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "project",
    "query": {}
   },
   {
    "name": "redis_instance",
    "label": "redis_instance",
    "query": {}
   },
   {
    "name": "role",
    "label": "role",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Uptime",
   "type": "timeseries",
   "description": "Uptime of the currently running Redis server process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/server/uptime"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "timeseries",
   "description": "CPU usage time per minute used by the Redis server, broken down by the system/user space and parent/child relationship. CPU seconds shows a total of all threads for the redis server main process. If you want to see the CPU usage for the main thread only, you can view the Main Thread CPU Seconds metric.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/cpu_utilization"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "description": "The ratio of successful Redis database calls and unsuccessful calls. A call is successful when the Redis database returns the value which the caller requested. A higher cache-hit ratio means the cache is being more fully utilized, which is beneficial for your application.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/cache_hit_ratio"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Bytes pending replication",
   "type": "timeseries",
   "description": "\tThe number of bytes that have not been replicated to the replica. This is the difference between replication byte offset (primary) and replication byte offset (replica). You will observe an increase in bytes pending as the primary replicates to the replica during a failover.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/replication/offset_diff"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Calls",
   "type": "timeseries",
   "description": "The number of Redis commands made per minute on your Redis instance. These include all open source Redis commands such as SET, GET, HSET, etc. This metric does not count Memorystore for Redis commands like 'create', 'update', etc.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/commands/calls"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "timeseries",
   "description": "Connected clients: The number of clients connected to the Redis instance.\nBlocked Clients: Number of blocked clients.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/clients/connected"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    },
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/clients/blocked"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Evicted keys/ Expired keys",
   "type": "timeseries",
   "description": "Evicted keys: The number of keys evicted due to the maxmemory limit.\nExpired keys: The number of keys that have an expiration set in this instance. If empty, the chart for this metric displays \"no data\".",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/evicted_keys"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    },
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/expired_keys"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Keys in database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/keyspace/keys"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    },
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/keyspace/keys_with_expiration"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Max memory / Memory usage",
   "type": "timeseries",
   "description": "Memory usage compared to the maxmemory limit for your instance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/memory/usage"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    },
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/memory/maxmemory"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Network bytes in/out",
   "type": "timeseries",
   "description": "Number of bytes sent and received by the instance over a given period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "metric.label.role",
       "=~",
       "$role",
       "AND",
       "resource.label.instance_id",
       "=~",
       "$redis_instance",
       "AND",
       "metric.type",
       "=",
       "redis.googleapis.com/stats/network_traffic"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$project"
     }
    }
   ]
  }
 ]
}