kind: Service
apiVersion: v1
metadata:
  name: bdrck-traces-gateway-otel-col-headless-ctrlpln
  namespace: observability
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: bdrck-traces-gateway-ctrlpln
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
  ports:
  - name: otlp
    protocol: TCP
    appProtocol: grpc
    port: 4317
    targetPort: 4317
