apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: bdrck-otel-instrumentation
  namespace: observability
spec:
  exporter:
    endpoint: http://bdrck-instrumentation-gateway-ctrlpln-opentelemetry-collector.observability.svc.cluster.local:4317
  propagators:
    - b3multi
    - b3
    - baggage
    - tracecontext
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: "none"
      - name: OTEL_INSTRUMENTATION_MICROMETER_ENABLED
        value: "false"
      - name: OTEL_SEMCONV_STABILITY_OPT_IN
        value: "http"
