apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: NotificationPolicy
metadata:
  annotations:
    meta.upbound.io/notify-id: jedi-slack-notify
  labels:
    testing.upbound.io/notify-name: jedi-slack-notify
  name: jedi-slack-notify
spec:
  providerConfigRef:
    name: grafana-cloud-provider-config
  forProvider:
    # disableProvenance: true
    contactPointSelector:
      matchLabels:
        testing.upbound.io/cp-name: jedi-slack
    groupBy:
      - "grafana_folder"
      - "alertname"
    groupInterval: 10s
    groupWait: 45s
    repeatInterval: 5m
    policy:
      - contactPoint: "jedi-slack"
      # - contactPointSelector:
      #     matchLabels:
      #       testing.upbound.io/cp-name: jedi-slack
        continue: true
        groupInterval: 10s
        groupWait: 45s
        matcher:
          - label: team
            match: =
            value: jedi
          - label: env
            match: =
            value: preview
