apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: observability-cred-replication
  namespace: observability
spec:
  components:
    - name: grafana-cloud
      type: ref-objects
      properties:
        objects:
          - resource: secret
            name: grafana-cloud
    - name: mongodb-grafana-wrkld
      type: ref-objects
      properties:
        objects:
          - resource: secret
            name: mongodb-grafana-wrkld
  policies:
    - name: topology-us-central-1
      type: topology
      properties:
        clusterLabelSelector:
          region: us-central1
